### ISSUE TITLE
`urandomm(n)` returns two values for certain numerical objects

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#23]
Hi. There seems to be a minor issue inside `urandomm(n)` when `n` is an integer of type `Math::GMPq` (or `Math::AnyNum`). Namely, it returns two values (the same value twice).

Example:
```perl
use 5.014;
use warnings;

use Math::GMPq;  # same for Math::AnyNum
use Math::Prime::Util qw(urandomm);

my $n = Math::GMPq->new(100);

say "urandomm($n) = (", join(', ', urandomm($n)), ')';
```

Output:
```
urandomm(100) = (80, 80)
```

Tested with MPU version 0.67.

**Comment by danaj** [comment]
It seems to be something with OBJECTIFY_RESULT.  Math::GMPq and Math::AnyNum are not recognized bigint classes (perhaps they should be?) so we skip the C path and go ask MPU::GMP and/or Perl for the answer.  Since the former returns a string for bigints I call another function to turn that into an object if needed.  I'll continue to look.

**Comment by danaj** [comment]
It looks like a POPs added to the generic objectify code after the dSP; manages to do it.  A single result of the type that was passed in is returned.

**Comment by trizen** [comment]
Thank you for the very quick fix. (https://github.com/danaj/Math-Prime-Util/commit/14a7888fa40de899723327b22f99b9b394780876)

Regarding the recognition of `Math::GMPq` and `Math::AnyNum` as bigint classes, personally I don't think it's necessarily as they are not integer-exclusive classes and not so popular either, which means that an object of this kind will be passed to MPU quite rarely to make it worth the change. Your call.
