### ISSUE TITLE
Incorrect values from prime_count(n, m) with 3 <= n <= 7

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#24]
Hi. I just discovered a minor issue in `prime_count(n, m)` when `n` is in the range `[3, 7]` (the number of primes bellow `n` are not subtracted from `prime_count(m)`).

Here is some code with a few test cases (comparing `Math::Prime::Util::GMP::prime_count()` (correct) with `ntheory::prime_count()` (incorrect)):
```perl
use 5.014;

use ntheory;
use Math::Prime::Util::GMP;

my @tests = (
    [3, 72520],
    [4, 61747],
    [5, 49220],
    [6, 86294],
    [7, 17144],
);

foreach my $range (@tests) {
    my $c1 =                ntheory::prime_count($range->[0], $range->[1]);  # incorrect
    my $c2 = Math::Prime::Util::GMP::prime_count($range->[0], $range->[1]);  # correct

    if ($c1 != $c2) {
        say "Error for prime_count(@$range): $c1 != $c2";
    }
}
```

Output:
```text
Error for prime_count(3 72520): 7173 != 7172
Error for prime_count(4 61747): 6212 != 6210
Error for prime_count(5 49220): 5060 != 5058
Error for prime_count(6 86294): 8391 != 8388
Error for prime_count(7 17144): 1975 != 1972
```

(under the current GitHub version of MPU)

**Comment by danaj** [comment]
Looks like this happened in v0.65.  Not good at all, thanks for finding.

**Comment by danaj** [comment]
bd9a409198115eb4c26f6bc0b8651bd65ec2aff3..c95d8f8f5f3700f7c7bc087ac8a8e937cbe70107 is when it first shows up in prime_count.  However that's because we switched algorithms.

The real bug showed up in 6c9362bf93bf8b65295e7d42279a787a66997850 when the prime count tables were redone in Aug 2016.  That is when _XS_segment_pi(3,72000) starts giving incorrect results.  The issue is in APPLY_TABLES.

**Comment by danaj** [comment]
Fix just pushed.  Also added a couple simple tests to the test suite as well as a more comprehensive test in xt/test-primecount.pl.

**Comment by trizen** [comment]
Fix confirmed.
