### ISSUE TITLE
[suggestion] Algorithm for counting k-smooth numbers <= n.

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#38]
It would be nice to have a new method, called `smooth_count(n,k)`, counting the number of k-smooth numbers <= n.

As a suggestion, I propose the following algorithm for exactly counting the number of k-smooth numbers <= n:

```perl
use 5.016;
use strict;
use warnings;

use Math::GMPz;
use Math::Prime::Util::GMP qw(powint logint prev_prime);

sub smooth_count {
    my ($n, $k) = @_;

    if (ref($n) ne 'Math::GMPz') {
        $n = Math::GMPz->new("$n");
    }

    if ($k < 2) {
        return 0;
    }

    my $count = sub {
        my ($n, $p) = @_;

        if ($p == 2) {
            return Math::GMPz::Rmpz_sizeinbase($n, 2);
        }

        my $t = Math::GMPz::Rmpz_init();
        my $q = prev_prime($p);

        my $count = 0;

        foreach my $k (0 .. logint($n, $p)) {

            Math::GMPz::Rmpz_ui_pow_ui($t, $p, $k);
            Math::GMPz::Rmpz_tdiv_q($t, $n, $t);

            $count += __SUB__->($t, $q);
        }

        $count;
    }->($n, prev_prime($k + 1));

    return $count;
}

say join(', ', map { smooth_count(powint(10, $_), 13) } 0..30);  #=> A106629
```

**Comment by danaj** [comment]
Did you see debruijn_psi added to the C code yesterday?  It's essentially the same algorithm but tries to avoid some extra recursion.  It's much faster.  But of course limited to 64-bits.

```
time mpu 'say join(" ",map{Math::Prime::Util::debruijn_psi(int(10**$_),31)} 0..18)'
1 10 82 434 1778 6070 18083 48366 118599 270648 581272 1185133 2309712 4326835 7826886 13723431 23398127 38897729 63198507

real	0m0.068s
user	0m0.064s
sys	0m0.004s

time mpu 'say Math::Prime::Util::debruijn_psi(2**30,1024)'
63750581

real	0m0.108s
user	0m0.108s
sys	0m0.000s
```


Unfortunately it still suffers as the sizes go up.

My inspiration was the recent Arxiv paper about random smooth integers, which is (sorta) saying, "enumerate the smooth numbers, now uniformly randomly select one from the list.  Then some tricks to not actually generate all of them.  That got me sidetracked on estimate including the Dickman rho function, which would be nice but is totally non-obvious in how to do precisely.  I then got somehow digressed into Liouville sums.

**Comment by danaj** [comment]
I finally got around to looking at this some more.  I'm running into the same API quandry as I did with almost primes, which is whether to use (n,k) or (k,n)  The former is what I started with, similar to is_smooth(n,k) or is_powerful(n,k).  The latter really makes sense since the k can be elided.  But most of the count functions take an optional range, e.g. prime_count(b) or prime_count(a,b) with the former really meaning (0,b).  Or with moebius where moebius(n) means get one value and moebius(a,b) means return an array for the range.  So with almost_primes I put the k first.

Now I'm looking at smooth_count(k,n) and rough_count(k,n).  Or maybe they should be (n,k)......

Internally the functions are debruijn_psi(n,k) and buchstab_phi(n,k) because that is what people are calling those functions.  The latter really just being a mapping onto the existing legendre_phi(n,p_n).  But the external API might be better leaving things open for a range.

@trizen if you have any thoughts on the argument order I'd love to hear.

**Comment by trizen** [comment]
In general, when `k` represents the order of the function or a small bound of some sort, I prefer `(n,k)` because sometimes `k` can be optional (like in `powerful_count(n, k=2)` and `divisor_sum(n, k=1)`), and having a consistent ordering is nice.

I'm used of thinking of the arguments in the following way: the important argument comes first (`n`) and the less important argument comes second (`k`).

But, in the end, I think it's just a matter of preference.

**Comment by danaj** [comment]
Checked in with tests, smooth_count(k,n) and rough_count(k,n).

The rough_count code uses legendre_phi, which is fast for some cases, slow for others.  There's a todo item from 2014 about trying to speed it up for some special cases, e.g. rough_count(10**13,10000).
