### ISSUE TITLE
Bad prototype for is_pseudoprime()?

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#50]
The following code:

```perl
use 5.014;
use Math::Prime::Util;

my @bases = (2);
# my @bases = (3,5);  # this works incorrectly

say Math::Prime::Util::is_pseudoprime(341, @bases);
```

dies with:

```
Base 1 is invalid at test.pl line 10.
```

**Comment by danaj** [comment]
I noticed this a while ago, and it's annoying.  The prototypes leave something to be desired.

1.  use '...' as the prototype and then do manual error checking for proper inputs.  The downside is that we lose compile-time checking for 'is_pseudoprime()' and 'is_pseudoprime($n)' which are both invalid.
2. Change the API slightly to use an implied base of 2, which is not out of line with the way I read it in some papers.

I'm thinking the second is the right way to do it.  I just did a small test and it seems to work (with no base, with 1 or more bases, with an empty array, and with a filled array).

**Comment by danaj** [comment]
Question.  If we call `@bases=();  say is_pseudoprime($n, @bases);` when should we expect?

1. Error.  This is the intention of the current code (one or more explicit bases are required).
2. Return 1, because it was a pseudoprime to all the given bases.
3. Return `is_pseudoprime($n,2)` because we have changed to an implicit base 2 if not given any bases.

Number 3 seems fine when called as `is_pseudoprime($n)` but it seems unintuitive if given an empty list.  Enough that I'm now dubious about the idea.

**Comment by trizen** [comment]
In my opinion, 3rd behavior is acceptable, and is justified by the explanation "when no base is given, base 2 is being used". And and empty list is equivalent with no base being given.

**Comment by danaj** [comment]
Finally checked in.

**Comment by trizen** [comment]
Thank you! :)
