### ISSUE TITLE
Test `t/70-rt-bignum.t` seems to hang with bignum >= 0.6x

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#57]
Test `t/70-rt-bignum.t` seems to hang with `bignum >= 0.6x`.

Probably because `bignum` now converts every literal number into a `Math::BigFloat` object (even when the literal number is actually an integer).

See: https://metacpan.org/dist/bignum/changes

This part of the test hangs (or takes a very long time):

```perl
use 5.010;
use Math::Prime::Util qw/:all/;
use Math::Prime::Util::PP;
use bignum;

say "bignum version: ", $bignum::VERSION;

my $n = 100199294509778143137521762187425301691197073534078445671945250753109628678272;
#my $n = Math::BigInt->new("100199294509778143137521762187425301691197073534078445671945250753109628678272");    # this works

say ref($n);
my @partial_factor = Math::Prime::Util::PP::prho_factor($n, 5);
say join " * ", @partial_factor;
```

Output:

```
bignum version: 0.62
Math::BigFloat
^C
```

**Comment by danaj** [comment]
Verified.

**Comment by danaj** [comment]
That test was bypassing the validation (which sanitizes the input to either a native or a Math::BigInt).  I moved the validation to the PP code so the test goes through the same code a normal call would.  The same should be done with some of the other *_factor() calls.

In the long term, the _validate_positive_integer() function should have an XS version used if possible, as it's quite slow in PP.  Which is why there's a sloppy push for validation in the PPFE code, so it's done as little as possible.
