### ISSUE TITLE
[github version] `nth_almost_prime(k, n)` sometimes returns 0

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util#71]
For some inputs, `nth_almost_prime(k,n)` incorrectly returns 0, as illustrated in the following example:

```perl
use 5.014;
use ntheory qw(:all);

say nth_almost_prime(100, 3);   #=> 0
say nth_almost_prime(100, 8);   #=> 6417481163655411345077059977216 (correct)
```

The 3rd 100-almost prime is `2852213850513516153367582212096`.

**Comment by trizen** [comment]
One more issue: `nth_almost_prime(41, 136192538)` dies with:

```
Parameter '4.39546081375562e+38' must be an integer at /usr/lib/perl5/5.36/site_perl/Math/Prime/Util/PP.pm line 3537.
```

**Comment by danaj** [comment]
The PP code for nth_almost_prime needs a lot of work.  The approximations and bounds for both count and nth are very, very conservative, which means we have a huge range.

Problem 1: we're going back and forth between floats and integers, and really not doing a good job keeping things straight.  I'm thinking I'm going to need something like "asint" or "intify" to convert arbitrary inputs into an integer.  Probably truncating in the case of float input.  This would speed things up, be simpler, and work better.  E.g. Perl's int(x) only works for some inputs.  Math::BigFloat has changed functions with different versions.

Problem 2:  We need much better upper / lower values.  Right now we get crazy values which means once we fix all the float / integer issues, we end up essentially hanging because the upper bound is many orders of magnitude too high for large k.

**Comment by danaj** [comment]
No longer dies with nth_almost_prime(41, 136192538).  However it takes about 9 minutes, because getting the almost_prime_count at this size is slow (14s on my laptop) and we call it many times in the final binary search.

An interpolating search would help.
